### ISSUE TITLE
Misleading error message for nvme info.

### ISSUE THREAD

**Issue by sbates130272** [OpenMPDK/xNVMe#304]
When one tries to get xnvme info on a device node that one does not have appropriate permissions for the error message returned seems misleading in the sense it states the file is not there. Would a more appropriate message not be to inform the user the file is there but they lack permissions to open it?

```
batesste@xnvme-test-qemu-1:~$ xnvme info /dev/nvme0
D nvme_init (src/nvme/core.c:514): nvme/core: could not get device class code
# ERR: 'xnvme_dev_open()': {errno: -2, msg: 'No such file or directory'}
batesste@xnvme-test-qemu-1:~$ sudo xnvme info /dev/nvme0
xnvme_dev:
  xnvme_ident:
    uri: '/dev/nvme0'
    dtype: 0x4
    nsid: 0x1
    csi: 0x1f
    subnqn: ''
  xnvme_be:
    admin: {id: 'file_as_ns'}
    sync: {id: 'psync'}
    async: {id: 'emu'}
    attr: {name: 'linux'}
  xnvme_opts:
    be: 'linux'
    mem: 'posix'
    dev: 'FIX-ID-VS-MIXIN-NAME'
    admin: 'file_as_ns'
    sync: 'psync'
    async: 'emu'
    oflags: 0x4
  xnvme_geo:
    type: XNVME_GEO_CONVENTIONAL
    npugrp: 1
    npunit: 1
    nzone: 1
    nsect: 1
    nbytes: 1
    nbytes_oob: 0
    tbytes: 0
    mdts_nbytes: 65024
    lba_nbytes: 512
    lba_extended: 0
    ssw: 9
```
