### ISSUE TITLE
Unable to open device with PCI URI

### ISSUE THREAD

**Issue by pcwilcox** [OpenMPDK/xNVMe#6]
After configuring and installing

```
$  ./configure --enable-debug --disable-tests --disable-examples --disable-tools --disable-tools-fio --enable-be-spdk
$ make
$ sudo make install
```

And building the example application, using the pci identifier to enable the SPDK backend:

```
#include <stdio.h>
#include <libxnvme.h>

int
main(int argc, char** argv)
{
    struct xnvme_dev* dev = xnvme_dev_open("pci://0000:af:00.0");
    if (!dev) {
        perror("xnvme_dev_open");
        return 1;
    }
    xnvme_dev_pr(dev, XNVME_PR_DEF);
    xnvme_dev_close(dev);

    return 0;
}
```

This address corresponds to the NVMe SSD on my system:
```
af:00.0 Non-Volatile memory controller: Samsung Electronics Co Ltd NVMe SSD Controller PM173X
```

Expected behavior is something like the example output in the docs. Instead I get:
```
xnvme_dev_open: No such device or address
```

I've tried numerous variations on the PCI string but none have worked. What is the needed configuration to enable the SPDK backend?

**Comment by safl** [comment]
Ah, it probably needs the namespace identifier e.g.

```
struct xnvme_dev* dev = xnvme_dev_open("pci://0000:af:00.0?nsid=1");
```

For reference, running the cli-tool:

```
xnvme enum
```

Should output a list of available devices (controllers/namespaces), such as:

```
# xnvme_enumerate()
xnvme_enumeration:
  capacity: 98
  nentries: 2
  entries:
  - {trgt: '0000:03:00.0', schm: 'pci', opts: '?nsid=1', uri: 'pci:0000:03:00.0?nsid=1'}
  - {trgt: '0000:03:00.0', schm: 'pci', opts: '?nsid=2', uri: 'pci:0000:03:00.0?nsid=2'}
```
